### ISSUE TITLE
Player being stuck in the walls (right and left)

### ISSUE THREAD

**Issue by ghost** [sautax/space_colonizer#2]
this appens when the player moves to the wall then moving in the opposite direction

**Comment by Batch42** [comment]
Seems like the problem is you where relying on the keyboard spam to change the r and l variables. if you hold any key down you'll see it print once, wait, then spam afterwards. This creates the delay when you hit a wall and try to reverse direction. I fixed it by permanately setting l/r to 1 during a 'keypress' event, and setting them back to 0 following a 'keyrelease' event

**Comment by ghost** [comment]
Thank you for the commit :) it merged to master
